# Generated by Django 4.2.7 on 2025-08-08 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service_requests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_ar', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('description_ar', models.TextField(blank=True)),
                ('color', models.CharField(default='#007bff', help_text='Hex color code', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'File Categories',
                'db_table': 'file_categories',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255)),
                ('stored_filename', models.CharField(max_length=255, unique=True)),
                ('file_path', models.CharField(max_length=1000)),
                ('file_size', models.BigIntegerField()),
                ('mime_type', models.CharField(max_length=100)),
                ('file_hash', models.CharField(db_index=True, max_length=64)),
                ('folder_path', models.CharField(default='/', max_length=500)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('version_number', models.IntegerField(default=1)),
                ('preview_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed'), ('not_supported', 'Not Supported')], default='pending', max_length=20)),
                ('preview_path', models.CharField(blank=True, max_length=1000)),
                ('thumbnail_path', models.CharField(blank=True, max_length=1000)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_virus_scanned', models.BooleanField(default=False)),
                ('virus_scan_result', models.CharField(blank=True, max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='file_management.filecategory')),
                ('parent_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='file_management.file')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='service_requests.servicerequest')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'files',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FileShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('share_token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('can_download', models.BooleanField(default=True)),
                ('can_view_preview', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('max_downloads', models.IntegerField(blank=True, null=True)),
                ('download_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='file_management.file')),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_files', to=settings.AUTH_USER_MODEL)),
                ('shared_with', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'file_shares',
                'indexes': [models.Index(fields=['share_token'], name='file_shares_share_t_68bcb5_idx'), models.Index(fields=['expires_at'], name='file_shares_expires_1bc2a0_idx')],
            },
        ),
        migrations.CreateModel(
            name='FileDownload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('download_token', models.CharField(blank=True, max_length=255)),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('downloaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_downloads', to=settings.AUTH_USER_MODEL)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='file_management.file')),
            ],
            options={
                'db_table': 'file_downloads',
                'ordering': ['-downloaded_at'],
                'indexes': [models.Index(fields=['file'], name='file_downlo_file_id_65c025_idx'), models.Index(fields=['downloaded_by'], name='file_downlo_downloa_0d13dd_idx'), models.Index(fields=['downloaded_at'], name='file_downlo_downloa_6b0c4a_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['request'], name='files_request_820029_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['uploaded_by'], name='files_uploade_eeab7f_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['file_hash'], name='files_file_ha_3fed72_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['created_at'], name='files_created_ab727e_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['is_deleted'], name='files_is_dele_332ed5_idx'),
        ),
    ]
